[workspace]
members = [
	"bee-common/bee-common",
	"bee-common/bee-common-derive",
	"bee-crypto",
	"bee-message",
	"bee-network",
	"bee-pow",
	"bee-signing",
	"bee-snapshot",
	"bee-storage/bee-storage",
	"bee-tangle",
	"bee-ternary",
	"bee-test",
]
