[package]
name = "bee-message"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "message"]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-pow = { path = "../bee-pow" }

bech32 = "0.8"
digest = "0.9"
hex = "0.4"
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs", rev = "09ff1a94d6a87838589ccf1b874cfa3283a00f26", features = ["ed25519", "blake2b"] }
ref-cast = "1.0"
serde = { version = "1.0", optional = true }
thiserror = "1.0"

[dev-dependencies]
bee-test = { path = "../bee-test" }

num_cpus = "1.13"
